name: Обновление Vanilla Мостов

on:
  schedule:
    - cron: '0 */6 * * *' # Авто-запуск каждые 6 часов
  workflow_dispatch:      # Кнопка для ручного запуска

# ДОБАВЛЕНО: Разрешаем боту записывать изменения в репозиторий
permissions:
  contents: write

jobs:
  build-and-grab:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Установка зависимостей
      run: pip install requests

    - name: Сбор мостов
      run: python vanilla_grabber.py

    - name: Сохранение файла в репозиторий
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add vanilla_bridges.txt
        git commit -m "Автоматическое обновление списка ванильных мостов" || echo "Изменений нет"
        git push
